version: '3.8'

services:
  app:
    build:
      context: ./authorization-flow
      dockerfile: .docker/Dockerfile
    ports:
      - 3000:3000
    networks:
      - keycloak-network
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://db:3306/keycloak
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=root
    command: start-dev
    depends_on:
      db:
        condition: service_healthy
    networks:
      - keycloak-network
  db:
    image: mysql:8.0.30-debian
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=keycloak
    volumes:
      - .docker/dbdata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - keycloak-network
networks:
  keycloak-network:
    driver: bridge
